package generator

import (
	"encoding/xml"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/danieljhkim/local-data-platform/internal/config/schema"
)

// hadoopXMLConfig represents Hadoop-style XML configuration
type hadoopXMLConfig struct {
	XMLName    xml.Name            `xml:"configuration"`
	Properties []hadoopXMLProperty `xml:"property"`
}

type hadoopXMLProperty struct {
	Name  string `xml:"name"`
	Value string `xml:"value"`
}

// WriteHadoopXML writes properties to a Hadoop-style XML config file
func WriteHadoopXML(props []schema.Property, path string) error {
	// Convert to XML structure
	xmlConfig := hadoopXMLConfig{
		Properties: make([]hadoopXMLProperty, len(props)),
	}
	for i, p := range props {
		xmlConfig.Properties[i] = hadoopXMLProperty{
			Name:  p.Name,
			Value: p.Value,
		}
	}

	// Ensure directory exists
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("failed to create directory: %w", err)
	}

	// Marshal with indentation
	data, err := xml.MarshalIndent(xmlConfig, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal XML: %w", err)
	}

	// Add XML header
	output := []byte(xml.Header + string(data) + "\n")

	// Write file
	if err := os.WriteFile(path, output, 0644); err != nil {
		return fmt.Errorf("failed to write file: %w", err)
	}

	return nil
}

// WriteSparkConf writes properties to a Spark .conf file (key=value format)
func WriteSparkConf(props []schema.Property, path string) error {
	// Ensure directory exists
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("failed to create directory: %w", err)
	}

	// Group properties by category for readability
	var lines []string

	// Add header
	lines = append(lines, "########################################")
	lines = append(lines, "# Generated by local-data-platform")
	lines = append(lines, "########################################")
	lines = append(lines, "")

	// Find max key length for alignment
	maxKeyLen := 0
	for _, p := range props {
		if len(p.Name) > maxKeyLen {
			maxKeyLen = len(p.Name)
		}
	}

	// Write properties with aligned values
	for _, p := range props {
		padding := strings.Repeat(" ", maxKeyLen-len(p.Name)+2)
		lines = append(lines, fmt.Sprintf("%s%s%s", p.Name, padding, p.Value))
	}

	// Write file
	content := strings.Join(lines, "\n") + "\n"
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write file: %w", err)
	}

	return nil
}
